import type { PropsWithChildren } from "react";

import "./style.css";

export const metadata = {
    title: `Page ${process.env["NEXT_PUBLIC_ENV_NAME"]}`,
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="ja">
            <body>{children}</body>
        </html>
    );
}
